settings:
  name: "NetApp artificial intelligence solutions"
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    lipi_enabled: true
    harmony_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-ai.zip

product-family:
  name: NetApp solutions
  repo: netapp-solutions-family
  
sidebar:
  entries:
    - title: "Artificial intelligence solutions"
      url: /index.html
    - title: "What's new"
      url: /whats-new.html
    - section: ai-infrastructures
    - section: ai-data-pipelines
    - section: ai-use-cases
    - section: data-analytics
 #
    - title: "Videos"
      url: /videos/ai-ml-videos.html
    - title: "Blogs"
      url: /blogs.html
    - title: "Legal notices"
      url: /legal-notices.html

