settings:
  name: "Artificial Intelligence solutions"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  # harmony_enabled: true

sidebar: 
  entries:
  - title: Legal notices
    url: /legal-notices.html
